# Generated by Django 4.0 on 2022-09-13 06:10

from django.db import migrations, models
import django.db.models.deletion
import utils.helper_functions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Profile Id')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=utils.helper_functions.petDirectoryPath, verbose_name='Profile Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Profile Id')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=utils.helper_functions.userDirectoryPath, verbose_name='Cover Image')),
                ('profile_image', models.ImageField(blank=True, default='/defaults/avatar.png', null=True, upload_to=utils.helper_functions.userDirectoryPath, verbose_name='Profile Image')),
                ('bio', models.TextField(max_length=300, null=True, verbose_name='Bio')),
                ('gender', models.CharField(max_length=10, null=True, verbose_name='Gender')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePosts',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Post Id')),
                ('post', models.ImageField(upload_to=utils.helper_functions.postDirectoryPath, verbose_name='Post')),
                ('caption', models.TextField(blank=True, max_length=500, null=True, verbose_name='Caption')),
                ('like_count', models.IntegerField(default=0, verbose_name='Like Count')),
                ('share_count', models.IntegerField(default=0, verbose_name='Share Count')),
                ('unique_view_count', models.IntegerField(default=0, verbose_name='Unqiue View Count')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('pet_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.petprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.petprofile')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PostLikedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False, verbose_name='liked')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='users.profileposts')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_liked', to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='petprofile',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='users.userprofile'),
        ),
    ]
