# Generated by Django 4.0 on 2022-09-12 06:43

from django.db import migrations, models
import django.db.models.deletion
import utils.helper_functions


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefollowing',
            name='follower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.petprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='/defaults/avatar.png', null=True, upload_to=utils.helper_functions.userDirectoryPath, verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user'),
        ),
        migrations.CreateModel(
            name='PostLikedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False, verbose_name='liked')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='users.profileposts')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_liked', to='auth.user')),
            ],
        ),
    ]
