# Generated by Django 4.0 on 2022-09-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comment', models.TextField(max_length=500, verbose_name='User Comment')),
                ('like_count', models.IntegerField(default=0, verbose_name='Like Count')),
            ],
        ),
    ]
